# V1 build for story generator app
import os
from dotenv import find_dotenv, load_dotenv
import openai
import streamlit as st
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import base64
import requests

# Initialize environment variables
load_dotenv(find_dotenv())

# Running on streamlit cloud
openai.api_key = st.secrets["OPENAI_API_KEY"] 
SENDGRID_API_KEY = st.secrets["SENDGRID_API_KEY"]
FROM_EMAIL = st.secrets["FROM_EMAIL"]

# # Running locally to retrieve keys
# openai.api_key = os.getenv("OPENAI_API_KEY") 
# SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
# FROM_EMAIL = os.getenv("FROM_EMAIL")

# Streamlit app configuration
st.header("Personalized Children Story Generator")

your_name = st.text_input('Your Name')
your_email = st.text_input('Your Email (We will send the storybook here 🤩)')
child_name = st.text_input('Child Name')
child_age = st.text_input('Child Age')
child_interest = st.text_area('Child Interest (e.g., adventures, animals, science, etc.)')
story_objective = st.text_area('Story Objective (e.g., build courage, teach a lesson, entertain, etc.)')

def app():
    
    if st.button('🚀 Generate & Send Storybook'):
        personalized_story = generate_personalized_story(
            your_name=your_name,
            your_email=your_email,
            child_name=child_name,
            child_age=child_age,
            child_interest=child_interest,
            story_objective=story_objective
        )
        st.success("✅ Story generated!")
        
        # Generate PDF    
        def create_pdf(personalized_story, filename="storybook.pdf"):
            doc = SimpleDocTemplate(filename, pagesize=letter)
            styles = getSampleStyleSheet()

            story = []
            story.append(Paragraph("<b>AI Storybook</b>", styles["Title"]))
            story.append(Spacer(1, 20))

            # Split paragraphs by double newlines
            for paragraph in personalized_story.split("\n\n"):
                story.append(Paragraph(paragraph.strip(), styles["Normal"]))
                story.append(Spacer(1, 12))

            doc.build(story)
            
            return filename
        
        pdf_filename = create_pdf(personalized_story)
        st.success("📄 PDF storybook created!")
        print("PDF created:", pdf_filename) # test and to be removed
        
        # Encode PDF for SendGrid attachment
        with open(pdf_filename, "rb") as f:
            encoded_pdf = base64.b64encode(f.read()).decode()

        # Prepare email data for SendGrid
        email_subject = "Your AI-Generated Storybook"
        email_body = (
            "Hi there,\n\n"
            "Attached is your personalized storybook generated by our StoryGenerator AI.\n\n"
            "Enjoy reading with your loved ones!\n\n"
            "— The StoryGenerator Team"
        )

        data = {
            "personalizations": [
                {"to": [{"email": your_email}], "subject": email_subject}
            ],
            "from": {"email": FROM_EMAIL},
            "content": [{"type": "text/plain", "value": email_body}],
            "attachments": [
                {
                    "content": encoded_pdf,
                    "type": "application/pdf",
                    "filename": pdf_filename,
                    "disposition": "attachment",
                }
            ],
        }

        headers = {
            "Authorization": f"Bearer {SENDGRID_API_KEY}",
            "Content-Type": "application/json"
        }

        with st.spinner("📤 Sending storybook to your email..."):
            response = requests.post(
                "https://api.sendgrid.com/v3/mail/send",
                headers=headers,
                json=data
            )

        if response.status_code == 202:
            st.success(f"✅ Storybook sent successfully to {your_email}!")
        else:
            st.error(f"❌ Failed to send email. Error: {response.text}")
            
        with st.expander("Personalized Story"):
            st.text_area("Generated Personalized Story", 
                        personalized_story, height=500)

# Story generation function
def generate_personalized_story(your_name,
                                your_email,
                                child_name,
                                child_age,
                                child_interest,
                                story_objective):
    prompt_template = """ 
     Write a personalized story to {child_name}, who is {child_age} years old, and is interested in {child_interest}. 
    The story should aim to {story_objective}. 
    The story should be engaging, age-appropriate, imaginative and tailor to the child's interests.
    Make sure to incorporate the following elements in the personalized story:
        - A captivating beginning that grabs the child's attention.
        - A clear plot with a problem and a resolution.
        - Relatable characters that the child can connect with.
        - Vivid descriptions to stimulate the child's imagination.
        - A positive message or moral that aligns with the story objective.
    At the end of the story, include a short note from {your_name} to {child_name}, encouraging them to embrace the story's message.
    Also, make sure that the personalized story is typo free.
    """
    prompt = prompt_template.format(
         your_name=your_name,
         your_email=your_email,
         child_name=child_name,
         child_age=child_age,
         child_interest=child_interest,
         story_objective=story_objective)
    
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are an artful and masterful expert specializing for children storytelling."},
            {"role": "user", "content": prompt}
           ])
    return response.choices[0].message.content

# Main function to run the app
def main():
    app()
     
if __name__ == "__main__":
    main()

